0~~~~                            ~~ Monitor: 9c5dd087-a389-4487-b6ad-82983340bfc7
   2018-11-04 08h48.19.0129418   > Initializing TextFile handler (MaxCountPerFile = 20000).
   2018-11-04 08h48.19.0157230   < 
1~~~~                            ~~ Monitor: b542421e-63a1-4bd3-91d0-b5cbe0a34b54
   2018-11-04 08h48.19.2039880 i Topic: CK.Core.StObjContextRoot.Load
   2018-11-04 08h48.19.2045250 i > Loading dynamic 'CK.StObj.AutoAssembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   2018-11-04 08h48.19.2706387 i | > Initializing CK.DB.Auth.Package : IAuthenticationDatabaseService
   2018-11-04 08h48.19.2719145 i | <  | 1 conclusion:
                                 |    | 1 providers: GitHub
   2018-11-04 08h48.19.2732145 i < 
   2018-11-04 08h48.19.2733912 i Done.
-  2018-11-04 08h48.19.6726664 i [Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager] User profile is available. Using 'C:\Users\viara\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
-  2018-11-04 08h48.22.5329321   ConnectionId:0HLI2693ERE05
-  2018-11-04 08h48.22.6990887   RequestId:0HLI2693ERE05:00000001 RequestPath:/order
-  2018-11-04 08h48.22.7029997 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request starting HTTP/1.1 GET http://localhost:5000/order  
-  2018-11-04 08h48.22.7126984 i [Microsoft.AspNetCore.Cors.Infrastructure.CorsService] Policy execution successful.
-  2018-11-04 08h48.22.9363617   API.Controllers.OrderController.GetAllDetailedOrders (API)
-  2018-11-04 08h48.22.9377971 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Route matched with {action = "GetAllDetailedOrders", controller = "Order"}. Executing action API.Controllers.OrderController.GetAllDetailedOrders (API)
-  2018-11-04 08h48.22.9649683 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Executing action method API.Controllers.OrderController.GetAllDetailedOrders (API) - Validation state: Valid
-  2018-11-04 08h48.23.3881643 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Executed action API.Controllers.OrderController.GetAllDetailedOrders (API) in 447.9036ms
2~~~~                            ~~ Monitor: 5ccfece9-05fc-4b5d-a013-fb567d35989d
   2018-11-04 08h48.23.3912020 F Nom d'objet 'ITIH.vOrders' non valide.
                                    ┌──────────────────────────■ Exception: SqlException ■──────────────────────────
                                    | Message:    Nom d'objet 'ITIH.vOrders' non valide.
                                    | Stack:         at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
                                    |                at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
                                    |                at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                                    |             --- End of stack trace from previous location where exception was thrown ---
                                    |                at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
                                    |             --- End of stack trace from previous location where exception was thrown ---
                                    |                at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
                                    |                at API.Services.Order.OrderService.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 145
                                    |                at API.Services.Order.OrderService.GuardedGetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 44
                                    |                at API.Controllers.OrderController.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Controllers\OrderController.cs:line 25
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
                                    |                at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
                                    |                at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
                                    └─────────────────────────────────────────────────────────────────────────
   2018-11-04 08h48.23.4336246 i Done.
-  2018-11-04 08h48.23.4344116 E [Microsoft.AspNetCore.Server.Kestrel] Connection id "0HLI2693ERE05", Request id "0HLI2693ERE05:00000001": An unhandled exception was thrown by the application.
                                    ┌──────────────────────────■ Exception: AggregateException ■──────────────────────────
                                    | Message:    One or more errors occurred. (Nom d'objet 'ITIH.vOrders' non valide.)
                                    | Stack:         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
                                    |  ┌──────────────────────────■ [Aggregated Exceptions] ■──────────────────────────
                                    |  |  ┌──────────────────────────■ Exception: SqlException ■──────────────────────────
                                    |  |  | Message:    Nom d'objet 'ITIH.vOrders' non valide.
                                    |  |  | Stack:         at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
                                    |  |  |                at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
                                    |  |  |                at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                                    |  |  |             --- End of stack trace from previous location where exception was thrown ---
                                    |  |  |                at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
                                    |  |  |             --- End of stack trace from previous location where exception was thrown ---
                                    |  |  |                at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
                                    |  |  |                at API.Services.Order.OrderService.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 145
                                    |  |  |                at API.Services.Order.OrderService.GuardedGetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 44
                                    |  |  |                at API.Controllers.OrderController.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Controllers\OrderController.cs:line 25
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
                                    |  |  |                at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
                                    |  |  |                at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
                                    |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  └─────────────────────────────────────────────────────────────────────────
                                    └─────────────────────────────────────────────────────────────────────────
-  2018-11-04 08h48.23.4704185 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request finished in 768.1701ms 500 
-  2018-11-04 08h48.34.7195032   RequestId:0HLI2693ERE05:00000002 RequestPath:/order
-  2018-11-04 08h48.34.7195306 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request starting HTTP/1.1 GET http://localhost:5000/order  
-  2018-11-04 08h48.34.7195978 i [Microsoft.AspNetCore.Cors.Infrastructure.CorsService] Policy execution successful.
-  2018-11-04 08h48.34.7208510   API.Controllers.OrderController.GetAllDetailedOrders (API)
-  2018-11-04 08h48.34.7208663 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Route matched with {action = "GetAllDetailedOrders", controller = "Order"}. Executing action API.Controllers.OrderController.GetAllDetailedOrders (API)
-  2018-11-04 08h48.34.7209442 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Executing action method API.Controllers.OrderController.GetAllDetailedOrders (API) - Validation state: Valid
-  2018-11-04 08h48.34.7977936 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Executed action API.Controllers.OrderController.GetAllDetailedOrders (API) in 76.8995ms
3~~~~                            ~~ Monitor: 7bd57342-d5e8-425b-bf40-2fe3efba1ebf
   2018-11-04 08h48.34.7980701 F Nom d'objet 'ITIH.vOrders' non valide.
                                    ┌──────────────────────────■ Exception: SqlException ■──────────────────────────
                                    | Message:    Nom d'objet 'ITIH.vOrders' non valide.
                                    | Stack:         at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
                                    |                at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
                                    |                at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                                    |             --- End of stack trace from previous location where exception was thrown ---
                                    |                at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
                                    |             --- End of stack trace from previous location where exception was thrown ---
                                    |                at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
                                    |                at API.Services.Order.OrderService.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 145
                                    |                at API.Services.Order.OrderService.GuardedGetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 44
                                    |                at API.Controllers.OrderController.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Controllers\OrderController.cs:line 25
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
                                    |                at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
                                    |                at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
                                    └─────────────────────────────────────────────────────────────────────────
   2018-11-04 08h48.34.7989225 i Done.
-  2018-11-04 08h48.34.7990839 E [Microsoft.AspNetCore.Server.Kestrel] Connection id "0HLI2693ERE05", Request id "0HLI2693ERE05:00000002": An unhandled exception was thrown by the application.
                                    ┌──────────────────────────■ Exception: AggregateException ■──────────────────────────
                                    | Message:    One or more errors occurred. (Nom d'objet 'ITIH.vOrders' non valide.)
                                    | Stack:         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
                                    |  ┌──────────────────────────■ [Aggregated Exceptions] ■──────────────────────────
                                    |  |  ┌──────────────────────────■ Exception: SqlException ■──────────────────────────
                                    |  |  | Message:    Nom d'objet 'ITIH.vOrders' non valide.
                                    |  |  | Stack:         at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
                                    |  |  |                at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
                                    |  |  |                at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                                    |  |  |             --- End of stack trace from previous location where exception was thrown ---
                                    |  |  |                at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
                                    |  |  |             --- End of stack trace from previous location where exception was thrown ---
                                    |  |  |                at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
                                    |  |  |                at API.Services.Order.OrderService.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 145
                                    |  |  |                at API.Services.Order.OrderService.GuardedGetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 44
                                    |  |  |                at API.Controllers.OrderController.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Controllers\OrderController.cs:line 25
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
                                    |  |  |                at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
                                    |  |  |                at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
                                    |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  └─────────────────────────────────────────────────────────────────────────
                                    └─────────────────────────────────────────────────────────────────────────
-  2018-11-04 08h48.34.8002961 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request finished in 80.7581ms 500 
-  2018-11-04 08h48.51.0898488   ConnectionId:0HLI2693ERE06
-  2018-11-04 08h48.51.0972051   RequestId:0HLI2693ERE06:00000001 RequestPath:/order
-  2018-11-04 08h48.51.0972245 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request starting HTTP/1.1 GET http://localhost:5000/order  
-  2018-11-04 08h48.51.0972927   API.Controllers.OrderController.GetAllDetailedOrders (API)
-  2018-11-04 08h48.51.0973099 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Route matched with {action = "GetAllDetailedOrders", controller = "Order"}. Executing action API.Controllers.OrderController.GetAllDetailedOrders (API)
-  2018-11-04 08h48.51.0973331 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Executing action method API.Controllers.OrderController.GetAllDetailedOrders (API) - Validation state: Valid
-  2018-11-04 08h48.51.1103872   ConnectionId:0HLI2693ERE07
-  2018-11-04 08h48.51.1644574 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Executed action API.Controllers.OrderController.GetAllDetailedOrders (API) in 67.1224ms
4~~~~                            ~~ Monitor: b307ff00-5690-435c-be2d-4b30933fceaa
   2018-11-04 08h48.51.1647662 F Nom d'objet 'ITIH.vOrders' non valide.
                                    ┌──────────────────────────■ Exception: SqlException ■──────────────────────────
                                    | Message:    Nom d'objet 'ITIH.vOrders' non valide.
                                    | Stack:         at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
                                    |                at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
                                    |                at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                                    |             --- End of stack trace from previous location where exception was thrown ---
                                    |                at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
                                    |             --- End of stack trace from previous location where exception was thrown ---
                                    |                at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
                                    |                at API.Services.Order.OrderService.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 145
                                    |                at API.Services.Order.OrderService.GuardedGetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 44
                                    |                at API.Controllers.OrderController.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Controllers\OrderController.cs:line 25
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
                                    |                at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
                                    |                at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
                                    └─────────────────────────────────────────────────────────────────────────
   2018-11-04 08h48.51.1658204 i Done.
-  2018-11-04 08h48.51.1659980 E [Microsoft.AspNetCore.Server.Kestrel] Connection id "0HLI2693ERE06", Request id "0HLI2693ERE06:00000001": An unhandled exception was thrown by the application.
                                    ┌──────────────────────────■ Exception: AggregateException ■──────────────────────────
                                    | Message:    One or more errors occurred. (Nom d'objet 'ITIH.vOrders' non valide.)
                                    | Stack:         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
                                    |  ┌──────────────────────────■ [Aggregated Exceptions] ■──────────────────────────
                                    |  |  ┌──────────────────────────■ Exception: SqlException ■──────────────────────────
                                    |  |  | Message:    Nom d'objet 'ITIH.vOrders' non valide.
                                    |  |  | Stack:         at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
                                    |  |  |                at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
                                    |  |  |                at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                                    |  |  |             --- End of stack trace from previous location where exception was thrown ---
                                    |  |  |                at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
                                    |  |  |             --- End of stack trace from previous location where exception was thrown ---
                                    |  |  |                at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
                                    |  |  |                at API.Services.Order.OrderService.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 145
                                    |  |  |                at API.Services.Order.OrderService.GuardedGetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 44
                                    |  |  |                at API.Controllers.OrderController.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Controllers\OrderController.cs:line 25
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
                                    |  |  |                at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
                                    |  |  |                at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
                                    |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  └─────────────────────────────────────────────────────────────────────────
                                    └─────────────────────────────────────────────────────────────────────────
-  2018-11-04 08h48.51.1669723 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request finished in 69.7524ms 500 
-  2018-11-04 08h48.57.0290257   ConnectionId:0HLI2693ERE08
-  2018-11-04 08h48.57.0312383   ConnectionId:0HLI2693ERE09
-  2018-11-04 08h48.57.0350180   RequestId:0HLI2693ERE09:00000001 RequestPath:/order
-  2018-11-04 08h48.57.0350686 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request starting HTTP/1.1 GET http://localhost:5000/order  
-  2018-11-04 08h48.57.0351288   API.Controllers.OrderController.GetAllDetailedOrders (API)
-  2018-11-04 08h48.57.0351381 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Route matched with {action = "GetAllDetailedOrders", controller = "Order"}. Executing action API.Controllers.OrderController.GetAllDetailedOrders (API)
-  2018-11-04 08h48.57.0351567 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Executing action method API.Controllers.OrderController.GetAllDetailedOrders (API) - Validation state: Valid
-  2018-11-04 08h48.57.0915596 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Executed action API.Controllers.OrderController.GetAllDetailedOrders (API) in 56.3945ms
5~~~~                            ~~ Monitor: f4325dee-46ac-40e8-a469-ce36ebb13105
   2018-11-04 08h48.57.0919650 F Nom d'objet 'ITIH.vOrders' non valide.
                                    ┌──────────────────────────■ Exception: SqlException ■──────────────────────────
                                    | Message:    Nom d'objet 'ITIH.vOrders' non valide.
                                    | Stack:         at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
                                    |                at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
                                    |                at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                                    |             --- End of stack trace from previous location where exception was thrown ---
                                    |                at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
                                    |             --- End of stack trace from previous location where exception was thrown ---
                                    |                at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
                                    |                at API.Services.Order.OrderService.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 145
                                    |                at API.Services.Order.OrderService.GuardedGetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 44
                                    |                at API.Controllers.OrderController.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Controllers\OrderController.cs:line 25
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
                                    |                at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
                                    |                at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
                                    └─────────────────────────────────────────────────────────────────────────
   2018-11-04 08h48.57.0927932 i Done.
-  2018-11-04 08h48.57.0929490 E [Microsoft.AspNetCore.Server.Kestrel] Connection id "0HLI2693ERE09", Request id "0HLI2693ERE09:00000001": An unhandled exception was thrown by the application.
                                    ┌──────────────────────────■ Exception: AggregateException ■──────────────────────────
                                    | Message:    One or more errors occurred. (Nom d'objet 'ITIH.vOrders' non valide.)
                                    | Stack:         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
                                    |  ┌──────────────────────────■ [Aggregated Exceptions] ■──────────────────────────
                                    |  |  ┌──────────────────────────■ Exception: SqlException ■──────────────────────────
                                    |  |  | Message:    Nom d'objet 'ITIH.vOrders' non valide.
                                    |  |  | Stack:         at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
                                    |  |  |                at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
                                    |  |  |                at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                                    |  |  |             --- End of stack trace from previous location where exception was thrown ---
                                    |  |  |                at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
                                    |  |  |             --- End of stack trace from previous location where exception was thrown ---
                                    |  |  |                at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
                                    |  |  |                at API.Services.Order.OrderService.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 145
                                    |  |  |                at API.Services.Order.OrderService.GuardedGetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 44
                                    |  |  |                at API.Controllers.OrderController.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Controllers\OrderController.cs:line 25
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
                                    |  |  |                at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
                                    |  |  |                at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
                                    |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  └─────────────────────────────────────────────────────────────────────────
                                    └─────────────────────────────────────────────────────────────────────────
-  2018-11-04 08h48.57.0939318 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request finished in 58.9012ms 500 
-  2018-11-04 08h49.23.6294281   RequestId:0HLI2693ERE09:00000002 RequestPath:/order
-  2018-11-04 08h49.23.6294411 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request starting HTTP/1.1 GET http://localhost:5000/order  
-  2018-11-04 08h49.23.6295013   API.Controllers.OrderController.GetAllDetailedOrders (API)
-  2018-11-04 08h49.23.6295097 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Route matched with {action = "GetAllDetailedOrders", controller = "Order"}. Executing action API.Controllers.OrderController.GetAllDetailedOrders (API)
-  2018-11-04 08h49.23.6295324 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Executing action method API.Controllers.OrderController.GetAllDetailedOrders (API) - Validation state: Valid
-  2018-11-04 08h49.23.6868666 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Executed action API.Controllers.OrderController.GetAllDetailedOrders (API) in 57.3309ms
6~~~~                            ~~ Monitor: cbaa8cc5-aa52-4a7e-9312-f1d56eb2a741
   2018-11-04 08h49.23.6871546 F Nom d'objet 'ITIH.vOrders' non valide.
                                    ┌──────────────────────────■ Exception: SqlException ■──────────────────────────
                                    | Message:    Nom d'objet 'ITIH.vOrders' non valide.
                                    | Stack:         at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
                                    |                at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
                                    |                at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                                    |             --- End of stack trace from previous location where exception was thrown ---
                                    |                at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
                                    |             --- End of stack trace from previous location where exception was thrown ---
                                    |                at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
                                    |                at API.Services.Order.OrderService.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 145
                                    |                at API.Services.Order.OrderService.GuardedGetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 44
                                    |                at API.Controllers.OrderController.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Controllers\OrderController.cs:line 25
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
                                    |                at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
                                    |                at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
                                    └─────────────────────────────────────────────────────────────────────────
   2018-11-04 08h49.23.6879309 i Done.
-  2018-11-04 08h49.23.6880343 E [Microsoft.AspNetCore.Server.Kestrel] Connection id "0HLI2693ERE09", Request id "0HLI2693ERE09:00000002": An unhandled exception was thrown by the application.
                                    ┌──────────────────────────■ Exception: AggregateException ■──────────────────────────
                                    | Message:    One or more errors occurred. (Nom d'objet 'ITIH.vOrders' non valide.)
                                    | Stack:         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
                                    |  ┌──────────────────────────■ [Aggregated Exceptions] ■──────────────────────────
                                    |  |  ┌──────────────────────────■ Exception: SqlException ■──────────────────────────
                                    |  |  | Message:    Nom d'objet 'ITIH.vOrders' non valide.
                                    |  |  | Stack:         at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
                                    |  |  |                at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
                                    |  |  |                at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                                    |  |  |             --- End of stack trace from previous location where exception was thrown ---
                                    |  |  |                at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
                                    |  |  |             --- End of stack trace from previous location where exception was thrown ---
                                    |  |  |                at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
                                    |  |  |                at API.Services.Order.OrderService.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 145
                                    |  |  |                at API.Services.Order.OrderService.GuardedGetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 44
                                    |  |  |                at API.Controllers.OrderController.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Controllers\OrderController.cs:line 25
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
                                    |  |  |                at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
                                    |  |  |                at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
                                    |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  └─────────────────────────────────────────────────────────────────────────
                                    └─────────────────────────────────────────────────────────────────────────
-  2018-11-04 08h49.23.6889234 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request finished in 59.4832ms 500 
-  2018-11-04 08h50.30.4035554   RequestId:0HLI2693ERE09:00000003 RequestPath:/order
-  2018-11-04 08h50.30.4035735 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request starting HTTP/1.1 GET http://localhost:5000/order  
-  2018-11-04 08h50.30.4036467   API.Controllers.OrderController.GetAllDetailedOrders (API)
-  2018-11-04 08h50.30.4036569 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Route matched with {action = "GetAllDetailedOrders", controller = "Order"}. Executing action API.Controllers.OrderController.GetAllDetailedOrders (API)
-  2018-11-04 08h50.30.4036820 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Executing action method API.Controllers.OrderController.GetAllDetailedOrders (API) - Validation state: Valid
-  2018-11-04 08h50.30.4599837 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Executed action API.Controllers.OrderController.GetAllDetailedOrders (API) in 56.3143ms
7~~~~                            ~~ Monitor: 891fe314-b911-4b00-83f7-374049b953a0
   2018-11-04 08h50.30.4637356 F Nom d'objet 'ITIH.vOrders' non valide.
                                    ┌──────────────────────────■ Exception: SqlException ■──────────────────────────
                                    | Message:    Nom d'objet 'ITIH.vOrders' non valide.
                                    | Stack:         at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
                                    |                at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
                                    |                at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                                    |             --- End of stack trace from previous location where exception was thrown ---
                                    |                at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
                                    |             --- End of stack trace from previous location where exception was thrown ---
                                    |                at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
                                    |                at API.Services.Order.OrderService.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 145
                                    |                at API.Services.Order.OrderService.GuardedGetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 44
                                    |                at API.Controllers.OrderController.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Controllers\OrderController.cs:line 25
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
                                    |                at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
                                    |                at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
                                    └─────────────────────────────────────────────────────────────────────────
   2018-11-04 08h50.30.4645036 i Done.
-  2018-11-04 08h50.30.4646079 E [Microsoft.AspNetCore.Server.Kestrel] Connection id "0HLI2693ERE09", Request id "0HLI2693ERE09:00000003": An unhandled exception was thrown by the application.
                                    ┌──────────────────────────■ Exception: AggregateException ■──────────────────────────
                                    | Message:    One or more errors occurred. (Nom d'objet 'ITIH.vOrders' non valide.)
                                    | Stack:         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
                                    |  ┌──────────────────────────■ [Aggregated Exceptions] ■──────────────────────────
                                    |  |  ┌──────────────────────────■ Exception: SqlException ■──────────────────────────
                                    |  |  | Message:    Nom d'objet 'ITIH.vOrders' non valide.
                                    |  |  | Stack:         at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
                                    |  |  |                at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
                                    |  |  |                at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                                    |  |  |             --- End of stack trace from previous location where exception was thrown ---
                                    |  |  |                at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
                                    |  |  |             --- End of stack trace from previous location where exception was thrown ---
                                    |  |  |                at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
                                    |  |  |                at API.Services.Order.OrderService.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 145
                                    |  |  |                at API.Services.Order.OrderService.GuardedGetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 44
                                    |  |  |                at API.Controllers.OrderController.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Controllers\OrderController.cs:line 25
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
                                    |  |  |                at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
                                    |  |  |                at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
                                    |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  └─────────────────────────────────────────────────────────────────────────
                                    └─────────────────────────────────────────────────────────────────────────
-  2018-11-04 08h50.30.4654984 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request finished in 61.9282ms 500 
-  2018-11-04 08h55.53.2178903   ConnectionId:0HLI2693ERE0A
-  2018-11-04 08h55.53.2188939   RequestId:0HLI2693ERE0A:00000001 RequestPath:/order
-  2018-11-04 08h55.53.2189570 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request starting HTTP/1.1 GET http://localhost:5000/order  
-  2018-11-04 08h55.53.2190224 i [Microsoft.AspNetCore.Cors.Infrastructure.CorsService] Policy execution successful.
-  2018-11-04 08h55.53.2190868   API.Controllers.OrderController.GetAllDetailedOrders (API)
-  2018-11-04 08h55.53.2191063 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Route matched with {action = "GetAllDetailedOrders", controller = "Order"}. Executing action API.Controllers.OrderController.GetAllDetailedOrders (API)
-  2018-11-04 08h55.53.2191504 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Executing action method API.Controllers.OrderController.GetAllDetailedOrders (API) - Validation state: Valid
-  2018-11-04 08h55.53.3321412 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Executed action API.Controllers.OrderController.GetAllDetailedOrders (API) in 113.0145ms
8~~~~                            ~~ Monitor: 17ccbecb-3c08-4803-8dd3-6c9630958470
   2018-11-04 08h55.53.3324806 F Nom d'objet 'ITIH.vOrders' non valide.
                                    ┌──────────────────────────■ Exception: SqlException ■──────────────────────────
                                    | Message:    Nom d'objet 'ITIH.vOrders' non valide.
                                    | Stack:         at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
                                    |                at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
                                    |                at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                                    |             --- End of stack trace from previous location where exception was thrown ---
                                    |                at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
                                    |             --- End of stack trace from previous location where exception was thrown ---
                                    |                at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
                                    |                at API.Services.Order.OrderService.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 145
                                    |                at API.Services.Order.OrderService.GuardedGetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 44
                                    |                at API.Controllers.OrderController.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Controllers\OrderController.cs:line 25
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
                                    |                at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
                                    |                at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
                                    └─────────────────────────────────────────────────────────────────────────
   2018-11-04 08h55.53.3333748 i Done.
-  2018-11-04 08h55.53.3334741 E [Microsoft.AspNetCore.Server.Kestrel] Connection id "0HLI2693ERE0A", Request id "0HLI2693ERE0A:00000001": An unhandled exception was thrown by the application.
                                    ┌──────────────────────────■ Exception: AggregateException ■──────────────────────────
                                    | Message:    One or more errors occurred. (Nom d'objet 'ITIH.vOrders' non valide.)
                                    | Stack:         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
                                    |  ┌──────────────────────────■ [Aggregated Exceptions] ■──────────────────────────
                                    |  |  ┌──────────────────────────■ Exception: SqlException ■──────────────────────────
                                    |  |  | Message:    Nom d'objet 'ITIH.vOrders' non valide.
                                    |  |  | Stack:         at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
                                    |  |  |                at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
                                    |  |  |                at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                                    |  |  |             --- End of stack trace from previous location where exception was thrown ---
                                    |  |  |                at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
                                    |  |  |             --- End of stack trace from previous location where exception was thrown ---
                                    |  |  |                at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
                                    |  |  |                at API.Services.Order.OrderService.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 145
                                    |  |  |                at API.Services.Order.OrderService.GuardedGetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 44
                                    |  |  |                at API.Controllers.OrderController.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Controllers\OrderController.cs:line 25
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
                                    |  |  |                at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
                                    |  |  |                at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
                                    |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  └─────────────────────────────────────────────────────────────────────────
                                    └─────────────────────────────────────────────────────────────────────────
-  2018-11-04 08h55.53.3344016 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request finished in 115.497ms 500 
-  2018-11-04 08h56.20.0269735   RequestId:0HLI2693ERE0A:00000002 RequestPath:/order
-  2018-11-04 08h56.20.0269870 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request starting HTTP/1.1 OPTIONS http://localhost:5000/order  
-  2018-11-04 08h56.20.0322159 i [Microsoft.AspNetCore.Cors.Infrastructure.CorsService] Policy execution successful.
9~~~~                            ~~ Monitor: 9fdfe200-9d28-4ada-904c-9a8f334a9f32
   2018-11-04 08h56.20.0342254 i Done.
-  2018-11-04 08h56.20.0360295 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request finished in 9.0397ms 204 
-  2018-11-04 08h56.20.0387648   RequestId:0HLI2693ERE0A:00000003 RequestPath:/order
-  2018-11-04 08h56.20.0387773 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request starting HTTP/1.1 GET http://localhost:5000/order  
-  2018-11-04 08h56.20.0388149 i [Microsoft.AspNetCore.Cors.Infrastructure.CorsService] Policy execution successful.
-  2018-11-04 08h56.20.0388404   API.Controllers.OrderController.GetAllDetailedOrders (API)
-  2018-11-04 08h56.20.0388474 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Route matched with {action = "GetAllDetailedOrders", controller = "Order"}. Executing action API.Controllers.OrderController.GetAllDetailedOrders (API)
-  2018-11-04 08h56.20.0388729 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Executing action method API.Controllers.OrderController.GetAllDetailedOrders (API) - Validation state: Valid
-  2018-11-04 08h56.20.0965117 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Executed action API.Controllers.OrderController.GetAllDetailedOrders (API) in 57.6369ms
A~~~~                            ~~ Monitor: fbfa73a9-5799-48eb-b97d-78a5f7ae112e
   2018-11-04 08h56.20.0968544 F Nom d'objet 'ITIH.vOrders' non valide.
                                    ┌──────────────────────────■ Exception: SqlException ■──────────────────────────
                                    | Message:    Nom d'objet 'ITIH.vOrders' non valide.
                                    | Stack:         at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
                                    |                at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
                                    |                at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                                    |             --- End of stack trace from previous location where exception was thrown ---
                                    |                at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
                                    |             --- End of stack trace from previous location where exception was thrown ---
                                    |                at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
                                    |                at API.Services.Order.OrderService.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 145
                                    |                at API.Services.Order.OrderService.GuardedGetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 44
                                    |                at API.Controllers.OrderController.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Controllers\OrderController.cs:line 25
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
                                    |                at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
                                    |                at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
                                    └─────────────────────────────────────────────────────────────────────────
   2018-11-04 08h56.20.0979044 i Done.
-  2018-11-04 08h56.20.0980161 E [Microsoft.AspNetCore.Server.Kestrel] Connection id "0HLI2693ERE0A", Request id "0HLI2693ERE0A:00000003": An unhandled exception was thrown by the application.
                                    ┌──────────────────────────■ Exception: AggregateException ■──────────────────────────
                                    | Message:    One or more errors occurred. (Nom d'objet 'ITIH.vOrders' non valide.)
                                    | Stack:         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
                                    |  ┌──────────────────────────■ [Aggregated Exceptions] ■──────────────────────────
                                    |  |  ┌──────────────────────────■ Exception: SqlException ■──────────────────────────
                                    |  |  | Message:    Nom d'objet 'ITIH.vOrders' non valide.
                                    |  |  | Stack:         at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
                                    |  |  |                at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
                                    |  |  |                at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                                    |  |  |             --- End of stack trace from previous location where exception was thrown ---
                                    |  |  |                at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
                                    |  |  |             --- End of stack trace from previous location where exception was thrown ---
                                    |  |  |                at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
                                    |  |  |                at API.Services.Order.OrderService.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 145
                                    |  |  |                at API.Services.Order.OrderService.GuardedGetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 44
                                    |  |  |                at API.Controllers.OrderController.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Controllers\OrderController.cs:line 25
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
                                    |  |  |                at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
                                    |  |  |                at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
                                    |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  └─────────────────────────────────────────────────────────────────────────
                                    └─────────────────────────────────────────────────────────────────────────
-  2018-11-04 08h56.20.0990657 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request finished in 60.2874ms 500 
-  2018-11-04 08h56.26.9859334   RequestId:0HLI2693ERE0A:00000004 RequestPath:/order
-  2018-11-04 08h56.26.9859515 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request starting HTTP/1.1 OPTIONS http://localhost:5000/order  
-  2018-11-04 08h56.26.9860466 i [Microsoft.AspNetCore.Cors.Infrastructure.CorsService] Policy execution successful.
B~~~~                            ~~ Monitor: cd211b3e-226f-47af-acc5-1d83f44f5c01
   2018-11-04 08h56.26.9861231 i Done.
-  2018-11-04 08h56.26.9861606 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request finished in 0.2105ms 204 
-  2018-11-04 08h56.26.9894557   RequestId:0HLI2693ERE0A:00000005 RequestPath:/order
-  2018-11-04 08h56.26.9894691 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request starting HTTP/1.1 GET http://localhost:5000/order  
-  2018-11-04 08h56.26.9895062 i [Microsoft.AspNetCore.Cors.Infrastructure.CorsService] Policy execution successful.
-  2018-11-04 08h56.26.9895308   API.Controllers.OrderController.GetAllDetailedOrders (API)
-  2018-11-04 08h56.26.9895382 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Route matched with {action = "GetAllDetailedOrders", controller = "Order"}. Executing action API.Controllers.OrderController.GetAllDetailedOrders (API)
-  2018-11-04 08h56.26.9895572 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Executing action method API.Controllers.OrderController.GetAllDetailedOrders (API) - Validation state: Valid
-  2018-11-04 08h56.27.0493109 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Executed action API.Controllers.OrderController.GetAllDetailedOrders (API) in 59.7527ms
C~~~~                            ~~ Monitor: 64ca3e7e-42b0-4b35-871d-ca7a3789948d
   2018-11-04 08h56.27.0495604 F Nom d'objet 'ITIH.vOrders' non valide.
                                    ┌──────────────────────────■ Exception: SqlException ■──────────────────────────
                                    | Message:    Nom d'objet 'ITIH.vOrders' non valide.
                                    | Stack:         at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
                                    |                at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
                                    |                at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                                    |             --- End of stack trace from previous location where exception was thrown ---
                                    |                at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
                                    |             --- End of stack trace from previous location where exception was thrown ---
                                    |                at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
                                    |                at API.Services.Order.OrderService.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 145
                                    |                at API.Services.Order.OrderService.GuardedGetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 44
                                    |                at API.Controllers.OrderController.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Controllers\OrderController.cs:line 25
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
                                    |                at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
                                    |                at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
                                    └─────────────────────────────────────────────────────────────────────────
   2018-11-04 08h56.27.0504198 i Done.
-  2018-11-04 08h56.27.0505738 E [Microsoft.AspNetCore.Server.Kestrel] Connection id "0HLI2693ERE0A", Request id "0HLI2693ERE0A:00000005": An unhandled exception was thrown by the application.
                                    ┌──────────────────────────■ Exception: AggregateException ■──────────────────────────
                                    | Message:    One or more errors occurred. (Nom d'objet 'ITIH.vOrders' non valide.)
                                    | Stack:         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
                                    |  ┌──────────────────────────■ [Aggregated Exceptions] ■──────────────────────────
                                    |  |  ┌──────────────────────────■ Exception: SqlException ■──────────────────────────
                                    |  |  | Message:    Nom d'objet 'ITIH.vOrders' non valide.
                                    |  |  | Stack:         at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
                                    |  |  |                at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
                                    |  |  |                at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                                    |  |  |             --- End of stack trace from previous location where exception was thrown ---
                                    |  |  |                at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
                                    |  |  |             --- End of stack trace from previous location where exception was thrown ---
                                    |  |  |                at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
                                    |  |  |                at API.Services.Order.OrderService.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 145
                                    |  |  |                at API.Services.Order.OrderService.GuardedGetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 44
                                    |  |  |                at API.Controllers.OrderController.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Controllers\OrderController.cs:line 25
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
                                    |  |  |                at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
                                    |  |  |                at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
                                    |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  └─────────────────────────────────────────────────────────────────────────
                                    └─────────────────────────────────────────────────────────────────────────
-  2018-11-04 08h56.27.0515602 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request finished in 62.0877ms 500 
-  2018-11-04 08h56.32.0367243   RequestId:0HLI2693ERE0A:00000006 RequestPath:/order
-  2018-11-04 08h56.32.0367373 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request starting HTTP/1.1 OPTIONS http://localhost:5000/order  
-  2018-11-04 08h56.32.0367827 i [Microsoft.AspNetCore.Cors.Infrastructure.CorsService] Policy execution successful.
D~~~~                            ~~ Monitor: 2ea57d22-8d3e-48d9-b451-859652674d79
   2018-11-04 08h56.32.0368231 i Done.
-  2018-11-04 08h56.32.0368462 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request finished in 0.1108ms 204 
-  2018-11-04 08h56.32.0788668   RequestId:0HLI2693ERE0A:00000007 RequestPath:/order
-  2018-11-04 08h56.32.0788807 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request starting HTTP/1.1 GET http://localhost:5000/order  
-  2018-11-04 08h56.32.0789132 i [Microsoft.AspNetCore.Cors.Infrastructure.CorsService] Policy execution successful.
-  2018-11-04 08h56.32.0789392   API.Controllers.OrderController.GetAllDetailedOrders (API)
-  2018-11-04 08h56.32.0789526 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Route matched with {action = "GetAllDetailedOrders", controller = "Order"}. Executing action API.Controllers.OrderController.GetAllDetailedOrders (API)
-  2018-11-04 08h56.32.0789739 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Executing action method API.Controllers.OrderController.GetAllDetailedOrders (API) - Validation state: Valid
-  2018-11-04 08h56.32.1470462 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Executed action API.Controllers.OrderController.GetAllDetailedOrders (API) in 68.0773ms
E~~~~                            ~~ Monitor: 7597ef5a-41e5-439e-b550-6f67fdb0f0ab
   2018-11-04 08h56.32.1473258 F Nom d'objet 'ITIH.vOrders' non valide.
                                    ┌──────────────────────────■ Exception: SqlException ■──────────────────────────
                                    | Message:    Nom d'objet 'ITIH.vOrders' non valide.
                                    | Stack:         at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
                                    |                at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
                                    |                at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                                    |             --- End of stack trace from previous location where exception was thrown ---
                                    |                at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
                                    |             --- End of stack trace from previous location where exception was thrown ---
                                    |                at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
                                    |                at API.Services.Order.OrderService.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 145
                                    |                at API.Services.Order.OrderService.GuardedGetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 44
                                    |                at API.Controllers.OrderController.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Controllers\OrderController.cs:line 25
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
                                    |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
                                    |                at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
                                    |                at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
                                    └─────────────────────────────────────────────────────────────────────────
   2018-11-04 08h56.32.1481040 i Done.
-  2018-11-04 08h56.32.1482107 E [Microsoft.AspNetCore.Server.Kestrel] Connection id "0HLI2693ERE0A", Request id "0HLI2693ERE0A:00000007": An unhandled exception was thrown by the application.
                                    ┌──────────────────────────■ Exception: AggregateException ■──────────────────────────
                                    | Message:    One or more errors occurred. (Nom d'objet 'ITIH.vOrders' non valide.)
                                    | Stack:         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
                                    |  ┌──────────────────────────■ [Aggregated Exceptions] ■──────────────────────────
                                    |  |  ┌──────────────────────────■ Exception: SqlException ■──────────────────────────
                                    |  |  | Message:    Nom d'objet 'ITIH.vOrders' non valide.
                                    |  |  | Stack:         at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
                                    |  |  |                at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
                                    |  |  |                at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                                    |  |  |             --- End of stack trace from previous location where exception was thrown ---
                                    |  |  |                at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
                                    |  |  |             --- End of stack trace from previous location where exception was thrown ---
                                    |  |  |                at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
                                    |  |  |                at API.Services.Order.OrderService.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 145
                                    |  |  |                at API.Services.Order.OrderService.GuardedGetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 44
                                    |  |  |                at API.Controllers.OrderController.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Controllers\OrderController.cs:line 25
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
                                    |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
                                    |  |  |                at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
                                    |  |  |                at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
                                    |  |  └─────────────────────────────────────────────────────────────────────────
                                    |  └─────────────────────────────────────────────────────────────────────────
                                    └─────────────────────────────────────────────────────────────────────────
-  2018-11-04 08h56.32.1491637 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request finished in 70.2839ms 500 
-  2018-11-04 08h56.48.7431350   RequestId:0HLI2693ERE0A:00000008 RequestPath:/order
-  2018-11-04 08h56.48.7431470 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request starting HTTP/1.1 OPTIONS http://localhost:5000/order  
-  2018-11-04 08h56.48.7431850 i [Microsoft.AspNetCore.Cors.Infrastructure.CorsService] Policy execution successful.
F~~~~                            ~~ Monitor: 78ec44df-7b4f-45bd-a0c0-e02859ddf7da
   2018-11-04 08h56.48.7432356 i Done.
-  2018-11-04 08h56.48.7432606 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request finished in 0.115ms 204 
-  2018-11-04 08h56.48.7696425   RequestId:0HLI2693ERE0A:00000009 RequestPath:/order
-  2018-11-04 08h56.48.7696578 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request starting HTTP/1.1 GET http://localhost:5000/order  
-  2018-11-04 08h56.48.7697028 i [Microsoft.AspNetCore.Cors.Infrastructure.CorsService] Policy execution successful.
-  2018-11-04 08h56.48.7697557   API.Controllers.OrderController.GetAllDetailedOrders (API)
-  2018-11-04 08h56.48.7697682 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Route matched with {action = "GetAllDetailedOrders", controller = "Order"}. Executing action API.Controllers.OrderController.GetAllDetailedOrders (API)
-  2018-11-04 08h56.48.7698011 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Executing action method API.Controllers.OrderController.GetAllDetailedOrders (API) - Validation state: Valid
-  2018-11-04 08h56.48.8391803 i [Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker] Executed action API.Controllers.OrderController.GetAllDetailedOrders (API) in 69.3985ms
10~~~~                            ~~ Monitor: debdef4a-9d68-4555-be6e-ba269160cbb9
    2018-11-04 08h56.48.8394242 F Nom d'objet 'ITIH.vOrders' non valide.
                                     ┌──────────────────────────■ Exception: SqlException ■──────────────────────────
                                     | Message:    Nom d'objet 'ITIH.vOrders' non valide.
                                     | Stack:         at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
                                     |                at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
                                     |                at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                                     |             --- End of stack trace from previous location where exception was thrown ---
                                     |                at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
                                     |             --- End of stack trace from previous location where exception was thrown ---
                                     |                at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
                                     |                at API.Services.Order.OrderService.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 145
                                     |                at API.Services.Order.OrderService.GuardedGetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 44
                                     |                at API.Controllers.OrderController.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Controllers\OrderController.cs:line 25
                                     |                at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
                                     |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
                                     |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
                                     |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
                                     |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                     |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
                                     |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
                                     |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
                                     |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                     |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
                                     |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
                                     |                at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
                                     |                at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
                                     └─────────────────────────────────────────────────────────────────────────
    2018-11-04 08h56.48.8402182 i Done.
-   2018-11-04 08h56.48.8403452 E [Microsoft.AspNetCore.Server.Kestrel] Connection id "0HLI2693ERE0A", Request id "0HLI2693ERE0A:00000009": An unhandled exception was thrown by the application.
                                     ┌──────────────────────────■ Exception: AggregateException ■──────────────────────────
                                     | Message:    One or more errors occurred. (Nom d'objet 'ITIH.vOrders' non valide.)
                                     | Stack:         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
                                     |  ┌──────────────────────────■ [Aggregated Exceptions] ■──────────────────────────
                                     |  |  ┌──────────────────────────■ Exception: SqlException ■──────────────────────────
                                     |  |  | Message:    Nom d'objet 'ITIH.vOrders' non valide.
                                     |  |  | Stack:         at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
                                     |  |  |                at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
                                     |  |  |                at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                                     |  |  |             --- End of stack trace from previous location where exception was thrown ---
                                     |  |  |                at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
                                     |  |  |             --- End of stack trace from previous location where exception was thrown ---
                                     |  |  |                at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
                                     |  |  |                at API.Services.Order.OrderService.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 145
                                     |  |  |                at API.Services.Order.OrderService.GuardedGetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Services\Order\OrderService.cs:line 44
                                     |  |  |                at API.Controllers.OrderController.GetAllDetailedOrders() in C:\Dev\repos\ITI-Human\API\Controllers\OrderController.cs:line 25
                                     |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
                                     |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
                                     |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
                                     |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
                                     |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                     |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
                                     |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
                                     |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
                                     |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
                                     |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
                                     |  |  |                at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
                                     |  |  |                at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
                                     |  |  |                at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
                                     |  |  └─────────────────────────────────────────────────────────────────────────
                                     |  └─────────────────────────────────────────────────────────────────────────
                                     └─────────────────────────────────────────────────────────────────────────
-   2018-11-04 08h56.48.8413038 i [Microsoft.AspNetCore.Hosting.Internal.WebHost] Request finished in 71.6474ms 500 
